import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<article>
					<div className={styles.flexHeader}>
						<h1 className="basic-heading">Antonio Enriquez</h1>
						<h1 className="basic-heading">Home</h1>
					</div>
					<div className="text-block">
						<div>
							New grad looking for more software development experience. Working
							at Gap in a rotational program. Currently in my front-end
							rotation.
						</div>
					</div>
					{/* <div className="text-block">
						<div className={styles.flexHeader}>
							<h1 className="basic-heading">Now</h1>
						</div>
						<div></div>
					</div> */}
				</article>
			</main>
			<footer className={styles.footer}></footer>
		</div>
	);
};

export default Home;
